name: gis-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=
  - numpy=
  - pandas=
  - geopy=
  - pvlib-python=
  - urllib3=
  - beautifulsoup4=
  - matplotlib=
  - requests=
  - pydantic=
  - jsonpickle
  - osmnx=
  - scikit-learn=
  - pyomo=5.7
  - haversine=
  - folium=
  - geopandas=
  - shapely=
  - networkx=
  - jinja2=
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0
    - gurobipy==9.5.1