name: gis-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=0.*
  - numpy=1.*
  - pandas=1.*
  - geopy=2.*
  - beautifulsoup4=4.*
  - matplotlib=3.*
  - requests=2.*
  - pydantic=1.*
  - jsonpickle=3.*
  - osmnx=1.1.*
  - pyomo=6.*
  - folium=0.*
  - geopandas=0.*
  - shapely=1.*
  - networkx=2.*
  - jinja2=3.*
  - pyscipopt=4.2.*
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0
    - gurobipy==9.5.1
    - highspy==1.5.0.dev0
    - coptpy==6.5.1