name: gis-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=
  - numpy=1.22.4
  - pandas=1.4.1
  - geopy=
  - pvlib-python=
  - urllib3=
  - beautifulsoup4=
  - matplotlib=
  - requests=
  - pydantic=
  - jsonpickle=
  - osmnx=1.1.2
  - scikit-learn=
  - pyomo=6.4.4
  - haversine=
  - folium=
  - geopandas=0.10.2
  - shapely=1.8.0
  - networkx=2.7.1
  - jinja2=
  - pyscipopt=4.2.0
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0
    - gurobipy==9.5.1
    - highspy
    - coptpy